# Generated by Django 5.0.6 on 2024-05-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_test_questions_question_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckQuestionBody',
            new_name='CheckBody',
        ),
        migrations.RenameModel(
            old_name='CodeQuestionBody',
            new_name='CodeBody',
        ),
        migrations.RenameModel(
            old_name='RadioQuestionBody',
            new_name='RadioBody',
        ),
        migrations.RenameModel(
            old_name='TextQuestionBody',
            new_name='TextBody',
        ),
    ]
