# Generated by Django 5.0.6 on 2024-05-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_checkquestionbody_checkbody_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('check', 'check'), ('code', 'code')], default='text', max_length=10, verbose_name='question type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.test'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='is_correct',
            field=models.BooleanField(default=True, verbose_name='is variant correct'),
        ),
    ]
