# Generated by Django 5.0.6 on 2024-05-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbody',
            old_name='answers',
            new_name='variants',
        ),
    ]
