# Generated by Django 5.0.6 on 2024-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_answers_textbody_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.CharField(verbose_name='variant text'),
        ),
    ]
