# Generated by Django 5.0.6 on 2024-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('questions', '0013_auto_20240517_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='available_for',
            field=models.ManyToManyField(default=(), related_name='available_tests', to='auth.group'),
        ),
    ]
