# Generated by Django 5.0.6 on 2024-05-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_test_available_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
    ]
