# Generated by Django 5.0.6 on 2024-06-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_remove_question_title_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbody',
            name='strict_score',
            field=models.BooleanField(default=True, verbose_name='is score calculation strict'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='points for question'),
        ),
    ]
