# Generated by Django 5.0.1 on 2024-03-30 11:53

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=511)),
                ('number_in_test', models.PositiveSmallIntegerField()),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('variants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=511)),
                ('number_in_test', models.PositiveSmallIntegerField()),
                ('testing_code', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadioQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=511)),
                ('number_in_test', models.PositiveSmallIntegerField()),
                ('answer', models.CharField(max_length=255)),
                ('variants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=511)),
                ('number_in_test', models.PositiveSmallIntegerField()),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testit_tests.checkquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testit_tests.codequestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadioAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testit_tests.radioquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('check_questions', models.ManyToManyField(to='testit_tests.checkquestion')),
                ('code_questions', models.ManyToManyField(to='testit_tests.codequestion')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('radio_questions', models.ManyToManyField(to='testit_tests.radioquestion')),
                ('text_questions', models.ManyToManyField(to='testit_tests.textquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_answers', models.ManyToManyField(to='testit_tests.checkanswer')),
                ('code_answers', models.ManyToManyField(to='testit_tests.codeanswer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('radio_answers', models.ManyToManyField(to='testit_tests.radioanswer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testit_tests.test')),
                ('text_answers', models.ManyToManyField(to='testit_tests.textanswer')),
            ],
        ),
        migrations.AddField(
            model_name='textanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testit_tests.textquestion'),
        ),
    ]
