# Generated by Django 5.0.6 on 2024-05-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
